### ISSUE TITLE
Roundup? StoryArc? What are they?

### ISSUE THREAD

**Issue by SleepingPanda** [anansi-project/comicinfo#36]
As a user I would very much appreciate more details about the metadata and how it's supposed to be populated. What exactly _is_ the definition of `StoryArc` within the context of the rfcs? Is it the name of a chapter? A collection of chapters? Furthermore, what is `ComicPageType: Roundup` (and the other page types for that matter)? These metadata fields are confusing and I can't find any details on how to use them as the needed context is missing from the [schema documentation](https://anansi-project.github.io/docs/comicinfo/documentation). If it's all explained somewhere, I'll ask that you please excuse my obtuseness and point me toward it! Also, I'd like to request Page Type: ToC.

**Comment by SenorSmartyPants** [comment]
My understanding of round up page type is a recap of previously in the story information.

**Comment by majora2007** [comment]
@SleepingPanda I will say all the major players in the scene support these tags and have documentation about tag use for their application. There is consensus to keep similar functionality between the applications to reduce strain on users, especially those who switch between different programs. 

I'd recommend checking out Komga or Kavita's wiki for how applications support ComicInfo.

**Comment by gotson** [comment]
@SleepingPanda the documentation is not exhaustive. We don't own the schema, it was developed by ComicRack and never documented, so people are using it in various ways. We are trying to document the accepted usage.

`StoryArc` was designed to store story arcs _within a series_

for instance if you look at [Undiscovered Country](https://comicvine.gamespot.com/undiscovered-country/4050-122630/), each group of 6 issues is a Story Arc, starting with Destiny, then Unity…

the thing is many people started using StoryArc for reading order, and Mylar was doing so, and the problem was that there wasn't any ordering possible with `StoryArc`, so after discussion between myself and evilhero we added  `StoryArcNumber`

`ComicPageTypes` is probably not used outside ComicRack

**Comment by gotson** [comment]
Reopening as we still need to document those fields.
