### ISSUE TITLE
Best practice in case of missing content

### ISSUE THREAD

**Issue by racine-p-a** [anansi-project/comicinfo#46]
Hello,
  I would like to know what is the best thing to do when a data is missing. Should we put the XML tag with empty content or just not putting it at all ?

In this example, there is no series or no series known.
```xml
  <?xml version="1.0" encoding="UTF-8"?>
<ComicInfo>
    <Title>My super book</Title>
    <Series></Series> <!-- Tag exists but is empty. -->
    <Year>2020</Year>
    <Month>2</Month>
    <Day>2</Day>
</ComicInfo>
  ```
```xml
  <?xml version="1.0" encoding="UTF-8"?>
<ComicInfo>
    <Title>My super book</Title>
    <!-- Tag is considered useless and is so removed. -->
    <Year>2020</Year>
    <Month>2</Month>
    <Day>2</Day>
</ComicInfo>
  ```
  
  Which one is the best behavior for your RFC ?
  
  Thanks for you job and your answers.

**Comment by gotson** [comment]
You probably already know the difference between the 2. An empty tag should mean that the value is blank, but is present. No tag should mean there is no information.

But that's irrelevant, because in the wild there's a bazillion files that are not following any standard.

Consuming applications should and will be very careful, and I don't think any would treat an empty but present tag as a blank value. I wouldn't.

**Comment by racine-p-a** [comment]
Indeed, that's what I thought/imagined/expected. But is there a norm or is the norm is `do not care and let the applications handles it` ?

**Comment by gotson** [comment]
There's no written norm, because it wouldn't help much as we are not any kind of authority about the format, and also because that specific use case is very rare. Metadata that is present but empty is not widespread.
