### ISSUE TITLE
Allow multiple values for the Web field

### ISSUE THREAD

**Issue by Shamicen** [anansi-project/comicinfo#56]
It would be nice if the standard allowed for multiple reference websites instead of just one. 

**What would need to be changed:**

Currently the documentation of the "Web" field states:

```
Web

A URL pointing to a reference website for the book.
```
This would need to be changed to:

```
Web

A URL pointing to a reference website for the book.

It is accepted that multiple values are comma separated.
```

**Comment by lordwelch** [comment]
It is undocumented but the Web field is actually space separated. You can test this by downloading ComicRack from here https://web.archive.org/web/20181018173957/http://comicrack.cyolito.com/downloads and if you put a space in-between it will only use the first item as the clickable link, this effectively makes the Web field a space separated field.
If you are wondering how to use a space in a URL you would % encode it like this `https://example.org/file%20with%%20space.txt`

**Comment by majora2007** [comment]
I think we should document that. I coded in Kavita allowing urls to be separated by a ;.

**Comment by lordwelch** [comment]
Yeah it's not well known but semicolons `;` are just a standard part of urls https://datatracker.ietf.org/doc/html/rfc2396#section-1.6 also spaces happen to be specifically excluded from the URI syntax https://datatracker.ietf.org/doc/html/rfc2396#section-2.4.3 because they are used as separators even though modern browsers will show URLs as  having a space, when you copy it it's always percent encoded
